# Generated by Django 4.0.5 on 2022-07-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_lot_user_comit_lot_user_comit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='user_comit',
            field=models.ManyToManyField(blank=True, related_name='usercomit', to='auctions.comit'),
        ),
    ]
