# Generated by Django 4.0.6 on 2022-08-07 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_lot_user_comit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time_lot',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='lot',
            name='sale',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lot',
            name='time_lot',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='lot',
            name='time_sales',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
