# Generated by Django 4.0.6 on 2022-08-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid_time_lot_lot_sale_lot_time_lot_lot_time_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
