# Generated by Django 4.1 on 2022-08-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_lot_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagetab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlimage', models.URLField(blank=True, max_length=512)),
                ('uploadimage', models.ImageField(blank=True, default=None, upload_to='uploads/')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='lotimage', to='auctions.imagetab'),
        ),
    ]
