# Generated by Django 4.1 on 2022-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_imagetab_lot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetab',
            name='uploadimage',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
