# Generated by Django 4.1 on 2022-08-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_imagetab_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='time_lot',
            field=models.DateTimeField(default=0),
        ),
    ]
