# Generated by Django 4.1 on 2022-08-28 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_lot_time_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='time_lot',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
