# Generated by Django 4.1 on 2022-08-28 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_lot_time_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='time_sales',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
